spring:
  application:
    name: ncds-message


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.245:10100/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 10085

ribbon:
  eureka:
    enabled: true
