spring:
  application:
    name: ncds-schedule
  cloud:
    loadbalancer:
      retry:
        enabled: false
server:
  port: 10083

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.245:10100/eureka/
    register-with-eureka: true
    fetch-registry: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
logging:
  config:
    classpath: logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ip:
      appname: ncds-schedule
      port: 6666
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: